# Generated by Django 3.2.4 on 2022-02-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comments',
        ),
    ]
