# Generated by Django 3.2.4 on 2022-03-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
